// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyf5dBeZtsHhaTOQrvy8MMHGbr7jGMh2Q',
    appId: '1:198485713151:web:919af9e12ab98ed4e7acca',
    messagingSenderId: '198485713151',
    projectId: 'anddumpfireauth',
    authDomain: 'anddumpfireauth.firebaseapp.com',
    databaseURL: 'https://anddumpfireauth.firebaseio.com',
    storageBucket: 'anddumpfireauth.appspot.com',
    measurementId: 'G-CNLDE32XN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdyNH8ZNEX4AwCQCrpTHTbp52kbCZ5OJU',
    appId: '1:198485713151:android:e4f2342297890562e7acca',
    messagingSenderId: '198485713151',
    projectId: 'anddumpfireauth',
    databaseURL: 'https://anddumpfireauth.firebaseio.com',
    storageBucket: 'anddumpfireauth.appspot.com',
  );
}
